# Generated by Django 5.1.7 on 2025-03-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Music', 'Music'), ('Sport', 'Sport'), ('Art', 'Art'), ('Theatre', 'Theatre'), ('Comedy', 'Comedy'), ('Festival', 'Festival'), ('Exhibition', 'Exhibition'), ('Conference', 'Conference'), ('Party', 'Party'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.DeleteModel(
            name='EventCategory',
        ),
    ]
