# Generated by Django 5.1.7 on 2025-03-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_home_addres_profile_home_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.TextField(default='[]'),
        ),
    ]
