# Generated by Django 5.1.7 on 2025-03-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='coordinates',
            field=models.TextField(),
        ),
    ]
