# Generated by Django 5.1.7 on 2025-03-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_alter_alert_coordinates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='coordinates',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='report_text',
        ),
        migrations.AddField(
            model_name='alert',
            name='address',
            field=models.CharField(default='Leżajsk, Mickiewicza 67', max_length=100),
        ),
    ]
