# Generated by Django 5.1.7 on 2025-03-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_transportrequest'),
        ('transport', '0006_rename_coordinates_alert_name_and_more'),
    ]

    operations = [
    ]
