# Generated by Django 5.1.7 on 2025-03-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_merge_20250314_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
