# Generated by Django 5.1.7 on 2025-03-14 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_alter_alert_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
