# Generated by Django 5.1.7 on 2025-03-15 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
